"""empty message

Revision ID: 342f9c2c0e62
Revises: 53a3ed792175
Create Date: 2021-04-18 16:20:31.183488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '342f9c2c0e62'
down_revision = '53a3ed792175'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'menu', ['id'])
    op.add_column('user', sa.Column('username', sa.String(length=80), nullable=False))
    op.drop_constraint('user_name_key', 'user', type_='unique')
    op.create_unique_constraint(None, 'user', ['id'])
    op.create_unique_constraint(None, 'user', ['username'])
    op.drop_column('user', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.create_unique_constraint('user_name_key', 'user', ['name'])
    op.drop_column('user', 'username')
    op.drop_constraint(None, 'menu', type_='unique')
    # ### end Alembic commands ###
