"""empty message

Revision ID: 4180a8a573b5
Revises: 342f9c2c0e62
Create Date: 2021-04-19 19:54:44.161912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4180a8a573b5'
down_revision = '342f9c2c0e62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('picture', sa.String(length=80), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu', 'picture')
    # ### end Alembic commands ###
