"""empty message

Revision ID: 7ad9f524ca6c
Revises: a41f78c6aaef
Create Date: 2021-04-21 06:33:27.987913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ad9f524ca6c'
down_revision = 'a41f78c6aaef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_px', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile_px')
    # ### end Alembic commands ###
