"""empty message

Revision ID: a41f78c6aaef
Revises: 23e8fcb2ad12
Create Date: 2021-04-19 20:27:49.333655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a41f78c6aaef'
down_revision = '23e8fcb2ad12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('menu_description_key', 'menu', type_='unique')
    op.drop_constraint('menu_title_key', 'menu', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('menu_title_key', 'menu', ['title'])
    op.create_unique_constraint('menu_description_key', 'menu', ['description'])
    # ### end Alembic commands ###
