"""empty message

Revision ID: b1c2a0bcb1c1
Revises: c2607f40bfaa
Create Date: 2021-04-26 12:00:57.264750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1c2a0bcb1c1'
down_revision = 'c2607f40bfaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'menu', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'menu', type_='unique')
    # ### end Alembic commands ###
